name: "Update flakes"

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # 01:15 every monday
    - cron:  '15 1 * * 1'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          inputs: nixpkgs
          # pr-labels: |                  # Labels to be set on the PR
          #   dependencies
          #   automated

