name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'This issue has been open for 30 days with no activity.'
          stale-pr-message: 'This PR has been open for 45 days with no activity. Remove stale label or comment, otherwise this will be closed in 5 days.'
          stale-issue-label: 'stale-issue'
          stale-pr-label: 'stale-pr'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: -1
          days-before-pr-close: 5

