name: publish_guide

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, Test, and Publish Guide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: type-description
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix --extra-experimental-features "nix-command flakes" build .#book
      - run: mkdir -p output/book output/description_viewer
      - run: cp -LR result/* output/book
      - run: nix --extra-experimental-features "nix-command flakes" build .#description_website_gh_pages
      - run: cp -LR result/* output/description_viewer
      - run: tree output
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        with:
          branch: gh-pages
          folder: output
